/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CartDtoApiResponse"];
                        "application/json": components["schemas"]["CartDtoApiResponse"];
                        "text/json": components["schemas"]["CartDtoApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddToCartRequest"];
                    "text/json": components["schemas"]["AddToCartRequest"];
                    "application/*+json": components["schemas"]["AddToCartRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CartDtoApiResponse"];
                        "application/json": components["schemas"]["CartDtoApiResponse"];
                        "text/json": components["schemas"]["CartDtoApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Cart/items/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductDtoIEnumerableApiResponse"];
                        "application/json": components["schemas"]["ProductDtoIEnumerableApiResponse"];
                        "text/json": components["schemas"]["ProductDtoIEnumerableApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddToCartRequest: {
            /** Format: int32 */
            productId?: number;
            /** Format: int32 */
            quantity?: number;
        };
        CartDto: {
            items?: components["schemas"]["CartItemDto"][] | null;
            /** Format: double */
            grandTotal?: number;
        };
        CartDtoApiResponse: {
            readonly success?: boolean;
            data?: components["schemas"]["CartDto"];
            readonly error?: string | null;
        };
        CartItemDto: {
            /** Format: int32 */
            productId?: number;
            productName?: string | null;
            /** Format: double */
            unitPrice?: number;
            /** Format: int32 */
            quantity?: number;
            /** Format: double */
            subtotal?: number;
        };
        ObjectApiResponse: {
            readonly success?: boolean;
            readonly data?: unknown;
            readonly error?: string | null;
        };
        ProductDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            /** Format: double */
            price?: number;
            category?: string | null;
        };
        ProductDtoIEnumerableApiResponse: {
            readonly success?: boolean;
            readonly data?: components["schemas"]["ProductDto"][] | null;
            readonly error?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
